version: '3.8'
services:
  front:
    build: .
    container_name: front
    ports:
      - "3334:3333"
    volumes:
      - .:/front
      # создаёт анонимный том для папки node_modules внутри контейнера. Это означает, что папка node_modules внутри контейнера не будет синхронизирована с аналогичной папкой на вашей локальной машине, и любые изменения в локальной папке node_modules не будут влиять на контейнер. Это позволяет контейнеру использовать свои собственные зависимости, установленные и оптимизированные для его среды.
      - /front/node_modules
